name: aider-from-issue

on:
  issues:
    types: [opened, edited]

jobs:
  respond-to-issue:
    runs-on: self-hosted
    if: github.event.issue.state == 'open'

    permissions:
      contents: write
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python & Aider
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Aider
        run: pip install aider-chat

      - name: Extract issue description as message
        run: |
          echo "${{ github.event.issue.body }}" > message.txt

      - name: Run Aider to edit files
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AIDER_MODEL: gpt-3.5-turbo
        run: |
          aider --no-gitignore --message-file final_prompt.txt > summary.txt
