name: summarize-pr

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  summarize-pr:
    runs-on: self-hosted

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Aider
        run: |
          pip install aider-chat

      - name: Generate PR diff
        run: |
          git fetch origin main
          git diff origin/main...HEAD > diff.txt

      - name: Combine prompt and diff
        run: |
          PROMPT=$(cat prompt.txt)
          DIFF=$(cat diff.txt | sed 's/"/\\"/g')
          echo "${PROMPT//\{\{diff\}\}/$DIFF}" > final_prompt.txt

      - name: Generate summary with Aider
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AIDER_MODEL: gpt-3.5-turbo
        run: |
          aider --no-gitignore --message-file final_prompt.txt > summary.txt

      - name: Post summary as PR comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: summary.txt
