name: aider-from-issue

on:
  issues:
    types: [opened, edited]

jobs:
  respond-to-issue:
    runs-on: self-hosted
    if: github.event.issue.state == 'open'

    permissions:
      contents: write
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python & Aider
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Aider
        run: pip install aider-chat

      - name: Extract issue description as message
        run: |
          echo "${{ github.event.issue.body }}" > message.txt

      - name: Run Aider to edit files
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AIDER_MODEL: gpt-3.5-turbo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          aider --message-file message.txt --yes

      - name: Commit & push changes
        run: |
          git add .
          git commit -m "游댢 Aider v치lasz az issue alapj치n: #${{ github.event.issue.number }}"
          git push origin HEAD

      - name: Capture git diff for comment
        run: |
          git diff HEAD~1 HEAD > diff.txt

      - name: Comment on the issue with changes
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Aider feldolgozta az al치bbi promptot, 칠s commitolta a v치ltoz치sokat:

            **V치ltoz치sok:**
            ```
            ${{ steps.capture_diff.outputs.diff }}
            ```

