name: PR Summary by OpenCode

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  summarize-pr:
    runs-on: self-hosted
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate summary with OpenCode
        run: |
          SUMMARY=$(opencode summarize .)
          echo "$SUMMARY" > summary.txt

      - name: Post summary as PR comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: summary.txt
